/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buoi3.gui.nhoma;

import com.mycompany.buoi3.model.PhongBan;
import connect.CommonSQL;
import connect.ketnoiSQLsever;
import constance.Constance;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Timkiem extends javax.swing.JFrame {
    Connection conn;
    /**
     * Creates new form Timkiem
     */
    public Timkiem() throws SQLException {
        conn = ketnoiSQLsever.getConnection(Constance.DB_URL, Constance.USER_NAME, Constance.PASSWORD);
        initComponents();
        if(conn!=null){
//            txtconnect.setText("kết nối SQL thành công");
        } else {
//            txtconnect.setText("kết nối không thành công");
        }   
        showCombobox();
        showTableDataFromSQL("all");
    }
    
    private void showCombobox(){
      String sql="SELECT  mapb, tenpb\n" +
                    "FROM      phong";
        try {
            ResultSet rs=CommonSQL.querySlect(sql,conn);
            while(rs.next()){
                String mapb=rs.getString("mapb");
                String tenpb=rs.getString("tenpb");
               
                PhongBan pb = new PhongBan(mapb,tenpb);
                cbphongban.addItem(pb);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmPhongBan.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void showTableDataFromSQL(String s){
         tb_ketqua.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {                       
                    },
                    new String [] {
                        "Mã NV","Họ và Tên","Giới tính","Ngày sinh","Tên Phòng Ban"
                    }
            ));
         String sql="";
         if(s.equals("all")){
               sql="SELECT nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv,  nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
                    "FROM nhanvien INNER JOIN\n" +
                    "phong ON nhanvien.mapb = phong.mapb";
         }else{
          sql="SELECT  nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv,  nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
               "FROM nhanvien INNER JOIN\n" +
                " phong ON nhanvien.mapb = phong.mapb where nhanvien.mapb = '"+s+"'";
         }
       ResultSet rs;
        try {
            int count=0;
            rs = CommonSQL.querySlect(sql,conn);
             while(rs.next()){
                 count++;
                String manv = rs.getString("manv");
                String honv = rs.getString("honv");
                String chulot = rs.getString("lotnv");
                Date namsinh = rs.getDate("namsinh");
                String tennv = rs.getString("tennv");
                String gioitinh="Nam";
                int gt=rs.getInt("gt");
                if (gt==0){
                    gioitinh="Nữ";
                }
                String tenpg=rs.getString("tenpb");
              
                String a[]=new String[]{manv,honv+" "+chulot+" "+tennv,gioitinh,namsinh.toString(),tenpg};
                ((DefaultTableModel)tb_ketqua.getModel()).addRow(a);
            }
             txtnum.setText(""+count);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPhongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chonfile = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbphongban = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ketqua = new javax.swing.JTable();
        btnexcel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtsearchten = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_tim_theo_ten = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnum1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbnamsinh = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_ket_qua_nam_sinh = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtnumnamsinh = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtnoidung = new javax.swing.JTextArea();
        btnopenfile = new javax.swing.JButton();
        btnghifile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("chọn phòng ban");

        cbphongban.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbphongbanItemStateChanged(evt);
            }
        });
        cbphongban.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbphongbanFocusGained(evt);
            }
        });
        cbphongban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbphongbanKeyReleased(evt);
            }
        });

        tb_ketqua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_ketqua);

        btnexcel.setText("xuất file Excel");
        btnexcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexcelMouseClicked(evt);
            }
        });

        jLabel2.setText("Tổng số nhân viên");

        txtnum.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbphongban, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnum)
                                .addGap(422, 422, 422)
                                .addComponent(btnexcel)))
                        .addGap(0, 529, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbphongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnexcel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtnum)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tìm theo phòng ban", jPanel1);

        jLabel3.setText("nhập tên cần tìm");

        txtsearchten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchtenKeyReleased(evt);
            }
        });

        tb_tim_theo_ten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_tim_theo_ten);

        jButton2.setText("xuất file Excel");

        jLabel4.setText("Tổng số nhân viên");

        txtnum1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnum1)
                                .addGap(400, 400, 400)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearchten, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 538, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsearchten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnum1))
                        .addGap(22, 22, 22))))
        );

        jTabbedPane1.addTab("tìm theo tên", jPanel2);

        jLabel5.setText("chọn năm sinh");

        cbnamsinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbnamsinhItemStateChanged(evt);
            }
        });
        cbnamsinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbnamsinhMouseClicked(evt);
            }
        });

        tb_ket_qua_nam_sinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_ket_qua_nam_sinh);

        jButton3.setText("xuất ra file Excel");

        jLabel6.setText("tổng số nhân viên");

        txtnumnamsinh.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnumnamsinh)
                                .addGap(406, 406, 406)
                                .addComponent(jButton3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 516, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnumnamsinh))
                        .addGap(30, 30, 30))))
        );

        jTabbedPane1.addTab("tìm theo ngày sinh", jPanel3);

        jLabel7.setText("nội dung lịch sử");

        txtnoidung.setColumns(20);
        txtnoidung.setRows(5);
        jScrollPane4.setViewportView(txtnoidung);

        btnopenfile.setText("mở file");
        btnopenfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenfileActionPerformed(evt);
            }
        });

        btnghifile.setText("ghi file");
        btnghifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghifileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 1060, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnopenfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnghifile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnopenfile)
                    .addComponent(btnghifile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("lịch sử log", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbphongbanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbphongbanItemStateChanged
        // TODO add your handling code here:
        PhongBan pb=(PhongBan)cbphongban.getSelectedItem();
        String mapb=pb.getMapb();
        showTableDataFromSQL(mapb);
    }//GEN-LAST:event_cbphongbanItemStateChanged

    private void txtsearchtenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchtenKeyReleased
        // TODO add your handling code here:
        showTableDataFromSQLTen(txtsearchten.getText());
    }//GEN-LAST:event_txtsearchtenKeyReleased

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        //tab 1
        if (jTabbedPane1.getSelectedIndex()==0){
            showCombobox();
            showTableDataFromSQL("all");
        }
          //tab 2
        if (jTabbedPane1.getSelectedIndex()==1){
            showTableDataFromSQLTen("");
        }
          //tab 3
        if (jTabbedPane1.getSelectedIndex()==2){
            for(int i=1970;i<=2010;i++){
                cbnamsinh.addItem(""+i);
            }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked
    
    
    private void cbphongbanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbphongbanKeyReleased
        // TODO add your handling code here:
        PhongBan pb=(PhongBan)cbphongban.getSelectedItem();
        String mapb=pb.getMapb();
        showTableDataFromSQL(mapb);
    }//GEN-LAST:event_cbphongbanKeyReleased

    private void cbphongbanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbphongbanFocusGained
        // TODO add your handling code here:
        PhongBan pb=(PhongBan)cbphongban.getSelectedItem();
        String mapb=pb.getMapb();
        showTableDataFromSQL(mapb);
    }//GEN-LAST:event_cbphongbanFocusGained

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        // TODO add your handling code here:
         if (jTabbedPane1.getSelectedIndex()==0){
            showCombobox();
//            showTableDataFromSQL("all");
        }
          //tab 2
        if (jTabbedPane1.getSelectedIndex()==1){
            showTableDataFromSQLTen("");
        }
          //tab 3
        if (jTabbedPane1.getSelectedIndex()==2){
            for(int i=1970;i<=2010;i++){
                cbnamsinh.addItem(""+i);
            }
            showTableDataFromSQLNamSinh("all");
        }
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void cbnamsinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbnamsinhItemStateChanged
        // TODO add your handling code here:
        String s = cbnamsinh.getSelectedItem().toString();
        showTableDataFromSQLNamSinh(s);
    }//GEN-LAST:event_cbnamsinhItemStateChanged

    private void cbnamsinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbnamsinhMouseClicked
        // TODO add your handling code here:
        String s = cbnamsinh.getSelectedItem().toString();
        showTableDataFromSQLNamSinh(s);
    }//GEN-LAST:event_cbnamsinhMouseClicked

    private void btnexcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexcelMouseClicked
        // TODO add your handling code here:
        try {
             // TODO add your handling code here:
             PhongBan pb=(PhongBan)cbphongban.getSelectedItem();
             String mapb=pb.getMapb();
             String sql="";
              
         if(mapb.equals("all")){
               sql="SELECT  nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv, nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
"FROM      nhanvien INNER JOIN\n" +
"                 phong ON nhanvien.mapb = phong.mapb";
         }else{
          sql="SELECT  nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv, nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
"FROM      nhanvien INNER JOIN\n" +
"                 phong ON nhanvien.mapb = phong.mapb where nhanvien.mapb ='"+mapb+"'";
         }
             ResultSet rs=CommonSQL.querySlect(sql, conn);
             
       //Instantiating the CSVWriter class
       Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        String path=s+"\\log\\output.csv";
       
//      com.opencsv.CSVWriter writer = new com.opencsv.CSVWriter(new FileWriter(path));
//      ResultSetMetaData Mdata = rs.getMetaData();
        com.opencsv.CSVWriter writer = new com.opencsv.CSVWriter(new OutputStreamWriter(new FileOutputStream(path), "UTF-8"));
        ResultSetMetaData Mdata = rs.getMetaData();
      Mdata.getColumnName(1);
      //Writing data to a csv file
      String line1[] = {Mdata.getColumnName(1), Mdata.getColumnName(2), Mdata.getColumnName(3),Mdata.getColumnName(4)};
      writer.writeNext(line1);
      String dataexcel[] = new String[5];
      while(rs.next()) {
         dataexcel[0] = rs.getString("manv");
         dataexcel[1] = rs.getString("honv");
         dataexcel[2] = rs.getString("lotnv");
         dataexcel[3] = rs.getString("tennv");
     
         writer.writeNext(dataexcel);
      }
      //Flushing data from writer to file
      writer.flush();
      System.out.println("Data entered");                               
             } catch (SQLException | IOException ex) {
             Logger.getLogger(Timkiem.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnexcelMouseClicked

    private void btnopenfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenfileActionPerformed
        // TODO add your handling code here:
        int result = chonfile.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            Path path = chonfile.getSelectedFile().toPath();
            System.out.println("path"+path);
            try {
                String contenString = "";
                for(String s : Files.readAllLines(path,StandardCharsets.UTF_8)){
                    contenString += s+ "\n";
                }
                txtnoidung.setText(contenString);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnopenfileActionPerformed

    private void btnghifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghifileActionPerformed
        // TODO add your handling code here:
        int result = chonfile.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
        // We'll be making a mytmp.txt file, write in there, then move it to
        // the selected
        // file. This takes care of clearing that file, should there be
        // content in it.
        File targetFile = chonfile.getSelectedFile();

        try {
            if (!targetFile.exists()) {
                targetFile.createNewFile();
            }

            FileWriter fw = new FileWriter(targetFile);

            fw.write(txtnoidung.getText());
            fw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnghifileActionPerformed
    
    private void showTableDataFromSQLTen(String s){
         tb_tim_theo_ten.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {                       
                    },
                    new String [] {
                        "Mã NV","Họ và Tên","Giới tính","Ngày sinh","Tên Phòng Ban"
                    }
            ));
         String sql;
         sql="SELECT nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv,  nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
                    "FROM nhanvien INNER JOIN\n" +
                    "phong ON nhanvien.mapb = phong.mapb where nhanvien.tennv like '%"+s+"%'";
       ResultSet rs;
        try {
            int count=0;
            rs = CommonSQL.querySlect(sql,conn);
             while(rs.next()){
                 count++;
                String manv = rs.getString("manv");
                String honv = rs.getString("honv");
                String chulot = rs.getString("lotnv");
                Date namsinh = rs.getDate("namsinh");
                String tennv = rs.getString("tennv");
                String gioitinh="Nam";
                int gt=rs.getInt("gt");
                if (gt==0){
                    gioitinh="Nữ";
                }
                String tenpg=rs.getString("tenpb");
              
                String a[]=new String[]{manv,honv+" "+chulot+" "+tennv,gioitinh,namsinh.toString(),tenpg};
                ((DefaultTableModel)tb_tim_theo_ten.getModel()).addRow(a);
            }
             txtnum1.setText(""+count);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPhongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void showTableDataFromSQLNamSinh(String s){
         tb_ket_qua_nam_sinh.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {                       
                    },
                    new String [] {
                        "Mã NV","Họ và Tên","Giới tính","Ngày sinh","Tên Phòng Ban"
                    }
            ));
         String sql;
         if(s.equals("all")){
               sql="SELECT nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv,  nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
                    "FROM nhanvien INNER JOIN\n" +
                    "phong ON nhanvien.mapb = phong.mapb";
         } else {
             sql = "SELECT nhanvien.manv, nhanvien.honv, nhanvien.lotnv, nhanvien.tennv,  nhanvien.gt, nhanvien.namsinh, phong.tenpb\n" +
                    "FROM nhanvien INNER JOIN\n" +
                    "phong ON nhanvien.mapb = phong.mapb where year(nhanvien.namsinh)= '"+s+"'";
         }
        
          
         
       ResultSet rs;
        try {
            int count=0;
            rs = CommonSQL.querySlect(sql,conn);
             while(rs.next()){
                count++;
                String manv=rs.getString("manv");
                String honv=rs.getString("honv");
                String lotnv=rs.getString("lotnv");
                Date namsinh=rs.getDate("namsinh");
                String tennv=rs.getString("tennv");
                String gioitinh="Nam";
                int gt=rs.getInt("gt");
                if (gt==0){
                    gioitinh="Nữ";
                }
                String tenpb=rs.getString("tenpb");
              
                String a[]=new String[]{manv,honv+" "+lotnv+" "+tennv,gioitinh,namsinh.toString(),tenpb};
            ((DefaultTableModel)tb_ket_qua_nam_sinh.getModel()).addRow(a);
            }
             txtnumnamsinh.setText(""+count);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPhongBan.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Timkiem().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Timkiem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexcel;
    private javax.swing.JButton btnghifile;
    private javax.swing.JButton btnopenfile;
    private javax.swing.JComboBox<String> cbnamsinh;
    private javax.swing.JComboBox<PhongBan> cbphongban;
    private javax.swing.JFileChooser chonfile;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tb_ket_qua_nam_sinh;
    private javax.swing.JTable tb_ketqua;
    private javax.swing.JTable tb_tim_theo_ten;
    private javax.swing.JTextArea txtnoidung;
    private javax.swing.JLabel txtnum;
    private javax.swing.JLabel txtnum1;
    private javax.swing.JLabel txtnumnamsinh;
    private javax.swing.JTextField txtsearchten;
    // End of variables declaration//GEN-END:variables

}
